// <auto-generated />
using System;
using Folders.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Folders.DAL.Migrations
{
    [DbContext(typeof(FolderAppContext))]
    partial class FolderAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Folders.DAL.Entities.Folder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Creating Digital Images"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Resources",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Evidence",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Graphic Products",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Primary Sources",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Secondary Sources",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Process",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Final Product",
                            ParentId = 4L
                        });
                });

            modelBuilder.Entity("Folders.DAL.Entities.Folder", b =>
                {
                    b.HasOne("Folders.DAL.Entities.Folder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Folders.DAL.Entities.Folder", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
